export const ADD_USER_TOKEN = "ADD_USER_TOKEN";
export const REMOVE_USER_TOKEN = "REMOVE_USER_TOKEN";

export const ADD_USER_DETAIL = "ADD_USER_DETAIL";
export const REMOVE_USER_DETAIL = "REMOVE_USER_DETAIL";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL";

export const USER_LOGOUT_REQUEST = "USER_LOGOUT_REQUEST";
export const USER_LOGOUT_SUCCESS = "USER_LOGOUT_SUCCESS";
export const USER_LOGOUT_FAIL = "USER_LOGOUT_FAIL";

export const USER_CONFIRMATION_REQUEST = "USER_CONFIRMATION_REQUEST";
export const USER_CONFIRMATION_SUCCESS = "USER_CONFIRMATION_SUCCESS";
export const USER_CONFIRMATION_FAIL = "USER_CONFIRMATION_FAIL";

export const USER_PAYMENT_REQUEST = "USER_PAYMENT_REQUEST";
export const USER_PAYMENT_SUCCESS = "USER_PAYMENT_SUCCESS";
export const USER_PAYMENT_FAIL = "USER_PAYMENT_FAIL";
